[workspace]
members = [
    "program"
]

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[toolchain]
anchor_version = "0.31.1"

[programs.localnet]
tally-subs = "eUV3U3e6zdQRXmAJFrvEFF9qEdWvjnQMA9BRxJef4d7"

[programs.devnet]
tally-subs = "6jsdZp5TovWbPGuXcKvnNaBZr1EBYwVTWXW1RhGa2JM5"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "cd tests && pnpm test"
