[workspace]
members = [
    "tally-subs"
]

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[toolchain]
anchor_version = "0.31.1"

[programs.localnet]
tally-subs = "Fwrs8tRRtw8HwmQZFS3XRRVcKBQhe1nuZ5heB4FgySXV"

[programs.devnet]
tally-subs = "6jsdZp5TovWbPGuXcKvnNaBZr1EBYwVTWXW1RhGa2JM5"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "cd tests && pnpm test"
