[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[toolchain]
anchor_version = "0.31.1"

[programs.localnet]
subs = "B9c98HcXYqVq2j48MLzFcbeDQbsUBMfYkDamLLsSHk1h"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "cd tests && pnpm test"
