[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[toolchain]
anchor_version = "0.31.1"

[programs.localnet]
subs = "B1P6DBXB17qq8cA7bAY7xhafCScRHuEQwTCyL67LFetU"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "pnpm test"
